version: "3"
services:
  ieuler-server:
    build: .
    ports:
      - 2718:2718
    entrypoint: ["gunicorn", "-b", "0.0.0.0:2718", "app:create_app()"]
  ieuler-db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306