version: "3"
services:
  ieuler-server:
    build: .
    ports:
      - 2718:2718
  ieuler-db:
    image: mysql
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306